### ISSUE TITLE
esy dependency causes error

### ISSUE THREAD

**Issue by kennetpostigo** [reasonml/reason-cli#10]
A user reported having issues with reason-cli installation. The error comes after the merging of my PR for berror. I'm not sure that the error didn't exist prior to my PR. The user was unblocked by running the following:
1. `npm uninstall -g esy && npm install -g "git://github.com/reasonml/esy.git#beta-v0.0.2"`
2. `npm uninstall -g git://github.com/reasonml/reason-cli.git   && npm install -g git://github.com/reasonml/reason-cli.git`

The difference is that they are installing esy globally prior to installation, i'm not certain why this happens and why the local esy dependency is not working. It may have to do with the fact that esy is available in the cli when globally installed as opposed to being tied to node_modules.

cc @jordwalke

**Comment by jordwalke** [comment]
1. We are not correctly failing when the npm install fails.
2. The install fails as you've mentioned and we should also fix that.
