### ISSUE TITLE
MBP install experience

### ISSUE THREAD

**Issue by glennsl** [reasonml/reason-cli#13]
This is on a first gen retina MBP, which has been upgraded to Sierra but never reinstalled. In other words, it's far from clean.

First attempt resutled in this error:
```
>> Fatal error: Module CamlinternalLazy unavailable.
```

Second attempt resolved that simply by being a second attempt, but now it fails with:
```
*** opam-installer-bin: building from source...
*** substs: building from source...
env: python2: No such file or directory
make: *** [substs.build] Error 127
make: *** Waiting for unfinished jobs....
env: python2: No such file or directory
make: *** [opam-installer-bin.build] Error 127
*** ocaml: building from source...
env: python2: No such file or directory
make: *** [ocaml.build] Error 127
```
There is no `python2` on my system, so I manually symlink it from `python27`. Still get the same error. Turns out my python is installed with macports which puts its stuff in `/opt/local`, so I put the symlink beside `python27` in `/opt/local/bin`, and for whatever reason that doesn't seem to jive with the installer. So I uninstall python from macports and reinstall it with homebrew. I've been told that will correctly set up the `python2` symlink for me. It doesn't. But i manually symlink it, now in `/usr/local/bin` and voilá. It works!

But it took a bit more tinkering than I'd like...

**Comment by jordwalke** [comment]
Thanks, [Here's](https://github.com/reasonml/esy/pull/9) the work to fix this by removing `python2` requirement. It's a known issue. Thanks for the patience - `reason-cli` isn't yet advertised because we haven't got the edge cases like this worked out yet. Soon though.

**Comment by jordwalke** [comment]
The core issue here is now fixed! No more python required.
The "CamlLazy" part is likely going to occur from time to time until we upgrade to 4.04, but it seems very infrequent for me and I install this thing several times a day. Happy to go further and fix that flakiness as well if it is still an issue in practice.
