### ISSUE TITLE
install fails on CentOS 7 with missing GLIBCXX_3.4.21

### ISSUE THREAD

**Issue by 108adams** [reasonml/reason-cli#57]
```
..../node_modules/reason-cli/r/_esyEjectRoot/bin/fastreplacestring.exe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ..../node_modules/reason-cli/r/_esyEjectRoot/bin/fastreplacestring.exe)
```

CentOS 7 provides 

```
strings /usr/lib64/libstdc++.so.6.0.19  | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBC_2.3
GLIBC_2.2.5
GLIBC_2.14
GLIBC_2.4
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

Does it mean there is no way to use reason-cli on this system?

**Comment by 108adams** [comment]
well, just found a note on the main page... it seems I need to setup a different VM just for reasonml :(

**Comment by andreypopp** [comment]
Hi, @108adams!

It's pretty easy to produce either a dev/pack-type release (in that case all deps will be built on the machin which performs the installation) or another bin-type release with a compatible glibc version. 

See https://github.com/reasonml/reason-cli#releasing and https://github.com/reasonml/reason-cli#using-pack-to-build-on-isolated-network-host-using-npm--g-on-the-destination for details.

Feel free to ask more questions about this.

cc @jordwalke probably we need to publish pack or dev releases too?

**Comment by 108adams** [comment]
Thanks, I managed to build and install the package on CentOS 7 with custom node 8.8.1 npm 5.3.0. 

If the glibc is not actually an issue, why do you constrict the version so tightly? Centos 7 is not an old distro, I know nothing about the other RedHat based ones, have you managed to install cli on Fedora or mandriva?

Anyway, thx for help, my reason  journey has started :)
