### ISSUE TITLE
How to install reason-cli without conflicting with my ocaml setup

### ISSUE THREAD

**Issue by Tav0** [reasonml/reason-cli#59]
I have an ocaml setup and use ocp-indent, but when I installed reason-cli it completely broke my ocaml editor setup

**Comment by Tav0** [comment]
Nevermind stupid me just found another ticket similar to mine #33 

This is really bad tho

**Comment by jordwalke** [comment]
Latest version is improved - but there still might be issues with other globals like `ocammerlin`. Let me know if you see other problems.

**Comment by Tav0** [comment]
@jordwalke thanks! Now it seems I can't install the cli as shown in the readme `npm install -g https://github.com/reasonml/reason-cli/archive/3.0.1-bin-darwin.tar.gz`

Takes stuck at initial start of install and then says `cb() never called`. I thought it was my npm that was having this issue, but I can still other modules just fine

**Comment by andreypopp** [comment]
@Tav0 looks like a network error (poorly handled by npm also). Are you getting this each time you do ```
$ npm install -g https://github.com/reasonml/reason-cli/archive/3.0.4-bin-linux.tar.gz
```

**Comment by Tav0** [comment]
@andreypopp You are right! Seems like it was a network issue through npm. I was getting this error everytime I was doing that ^ , but now seems to download just fine
