### ISSUE TITLE
rtop won't start: "syntax error near unexpected token `$'\001\001C'`"

### ISSUE THREAD

**Issue by micahscopes** [reasonml/reason-cli#67]
I'm running Arch linux.

I tried both `yarn global add reason-cli` and `npm -g reason-cli`. Both resulted in installation of `reason-cli@3.1.0-darwin`.  Confusing!  Running `rtop` gives me:
```
/home/micah/.npm-global/lib/node_modules/reason-cli/3_________________________________/i/opam__slash__utop-2.1.0-5c44d02e/bin/utop-full: line 2: syntax error near unexpected token `$'\001\001C''
/home/micah/.npm-global/lib/node_modules/reason-cli/3_________________________________/i/opam__slash__utop-2.1.0-5c44d02e/bin/utop-full: line 2: `T�W%.7@IR[gt}���c(C'
```

**Comment by micahscopes** [comment]
I just read the instructions... they say I'm supposed to install from a tarball, so I'm trying that now.  Hopefully it'll solve all my problems!

**Comment by micahscopes** [comment]
After trying several different releases, I finally was able to get things working with 3.1.0.  I used: `npm install -g reason-cli@3.1.0-linux --force`.  (I added `--force` so that npm would overwrite an existing ocamlmerlin binary.  no idea if that was a good idea, but it's what i had to do to get things working!)

**Comment by zploskey** [comment]
Instead of using `--force` you can `npm uninstall -g reason-cli` first. 3.1.0 isn't officially released yet, but this will all be explained in the instructions when it is.
