### ISSUE TITLE
refmt shows incorrect version

### ISSUE THREAD

**Issue by flash-gordon** [reasonml/reason-cli#69]
No matter what version of `reason-cli` you're on `refmt --version` stuck on `Reason 3.0.0 @ bee43b0`. Tested on 3.0.5 and 3.1.0.

**Comment by zploskey** [comment]
This should be fixed in the next release. See https://github.com/facebook/reason/pull/1849. Thanks for reporting.

**Comment by flash-gordon** [comment]
Good, I think we can close this one then
