### ISSUE TITLE
Repo size

### ISSUE THREAD

**Issue by kamilchm** [reasonml/reason-cli#72]
I wanted to clone this repo to tweak linux version a little but I found out it's 2GB in size. Is it possible to shrink it somehow?

**Comment by zploskey** [comment]
There are big release tags that get fetched when you do a normal clone. If you just clone the master branch using 
```
git clone --single-branch https://github.com/reasonml/reason-cli.git
```
it winds up being less than 400K for me. A clone with `--no-tags` is similarly small.

**Comment by kamilchm** [comment]
It's better now, thx!
