### ISSUE TITLE
refmt removes necessary parenthesis

### ISSUE THREAD

**Issue by vkammerer** [reasonml/reason-cli#74]
I don't know where an issue with `refmt` should be filed, so I apologize in advance if it should be posted elsewhere.

I was reading through [http://reasonmlhub.com/exploring-reasonml/ch_functions.html](http://reasonmlhub.com/exploring-reasonml/ch_functions.html) (the section "Compatibility of function types with labeled parameters"), and trying to reproduce the examples locally when I encountered what seems to be a bug with `refmt`'s handling of parenthesis.

Steps to reproduce:
- go to [https://reasonml.github.io/en/try.html?rrjsx=true&reason=DYUwLgBAhgJjEF4IAoB+APANBVBPAlIgHwToQDUEuA3AFCiQDGUwwAggGICuAdgOoBLMAAsArGx4wATIhRRuPAFwo06ZQJ5hsedZsIISGsPn0l5vZKOxT8dWgCkAzgDpgAewDmyZq069BIuKSUsiwMCZ0QA](https://reasonml.github.io/en/try.html?rrjsx=true&reason=DYUwLgBAhgJjEF4IAoB+APANBVBPAlIgHwToQDUEuA3AFCiQDGUwwAggGICuAdgOoBLMAAsArGx4wATIhRRuPAFwo06ZQJ5hsedZsIISGsPn0l5vZKOxT8dWgCkAzgDpgAewDmyZq069BIuKSUsiwMCZ0QA)
- as you can see, reason compiles correctly and the browser console logs the expected output.
- click on "refmt" and see how parenthesis are removed from the function's definition
- Trigger recompilation by adding a line break at the end
- reason cannot compile the code anymore and logs an error

**Comment by IwanKaramazow** [comment]
Hi @vkammerer.
If you have issues with refmt, you can file them at https://github.com/facebook/reason/issues.
This is indeed legit issue, I'll solve it.

**Comment by vkammerer** [comment]
Duplicate of https://github.com/facebook/reason/issues/1957
