### ISSUE TITLE
Unable to install using npm 6 and node 10 on clean fedora 28 

### ISSUE THREAD

**Issue by HristoKolev** [reasonml/reason-cli#76]
I'm running `npm install -g reason-cli@3.1.0-linux` and it errors out >

> [kenny@localhost /]$ npm install -g reason-cli@3.1.0-linux
> /home/kenny/.nvm/versions/node/v10.0.0/bin/ocamlmerlin -> /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli/.bin/ocamlmerlin
> /home/kenny/.nvm/versions/node/v10.0.0/bin/ocamlmerlin-reason -> /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli/.bin/ocamlmerlin-reason
> /home/kenny/.nvm/versions/node/v10.0.0/bin/utop -> /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli/.bin/utop
> /home/kenny/.nvm/versions/node/v10.0.0/bin/refmt -> /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli/.bin/refmt
> /home/kenny/.nvm/versions/node/v10.0.0/bin/reopt -> /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli/.bin/reopt
> /home/kenny/.nvm/versions/node/v10.0.0/bin/rebuild -> /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli/.bin/rebuild
> /home/kenny/.nvm/versions/node/v10.0.0/bin/rtop -> /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli/.bin/rtop
> /home/kenny/.nvm/versions/node/v10.0.0/bin/reactjs_jsx_ppx_v3 -> /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli/.bin/reactjs_jsx_ppx_v3
> /home/kenny/.nvm/versions/node/v10.0.0/bin/reactjs_jsx_ppx_v2 -> /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli/.bin/reactjs_jsx_ppx_v2
> /home/kenny/.nvm/versions/node/v10.0.0/bin/reason-cli-esy-sandbox -> /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli/.bin/reason-cli-esy-sandbox
> /home/kenny/.nvm/versions/node/v10.0.0/bin/refmttype -> /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli/.bin/refmttype
> 
> > reason-cli@3.1.0-linux postinstall /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli
> > ./bin/esyBuildRelease bin install
> 
> make: *** [/home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli/r/build-eject/Makefile:1104: /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli/r/build-eject//bin/fastreplacestring.exe] Error 127
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! reason-cli@3.1.0-linux postinstall: `./bin/esyBuildRelease bin install`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the reason-cli@3.1.0-linux postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/kenny/.npm/_logs/2018-05-08T09_49_43_294Z-debug.log
>

**Comment by HristoKolev** [comment]
Here is the log file: 

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/home/kenny/.nvm/versions/node/v10.0.0/bin/node',
> 1 verbose cli   '/home/kenny/.nvm/versions/node/v10.0.0/bin/npm',
> 1 verbose cli   'install',
> 1 verbose cli   '-g',
> 1 verbose cli   'reason-cli@3.1.0-linux' ]
> 2 info using npm@6.0.0
> 3 info using node@v10.0.0
> 4 verbose npm-session a9c797ee1672de5d
> 5 silly install loadCurrentTree
> 6 silly install readGlobalPackageData
> 7 http fetch GET 304 https://registry.npmjs.org/reason-cli 314ms (from cache)
> 8 silly pacote version manifest for reason-cli@3.1.0-linux fetched in 329ms
> 9 timing stage:loadCurrentTree Completed in 433ms
> 10 silly install loadIdealTree
> 11 silly install cloneCurrentTreeToIdealTree
> 12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
> 13 silly install loadShrinkwrap
> 14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
> 15 silly install loadAllDepsIntoIdealTree
> 16 silly resolveWithNewModule reason-cli@3.1.0-linux checking installable status
> 17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 3ms
> 18 timing stage:loadIdealTree Completed in 5ms
> 19 silly currentTree lib
> 20 silly idealTree lib
> 20 silly idealTree └── reason-cli@3.1.0-linux
> 21 silly install generateActionsToTake
> 22 timing stage:generateActionsToTake Completed in 3ms
> 23 silly diffTrees action count 1
> 24 silly diffTrees add reason-cli@3.1.0-linux
> 25 silly decomposeActions action count 8
> 26 silly decomposeActions fetch reason-cli@3.1.0-linux
> 27 silly decomposeActions extract reason-cli@3.1.0-linux
> 28 silly decomposeActions preinstall reason-cli@3.1.0-linux
> 29 silly decomposeActions build reason-cli@3.1.0-linux
> 30 silly decomposeActions install reason-cli@3.1.0-linux
> 31 silly decomposeActions postinstall reason-cli@3.1.0-linux
> 32 silly decomposeActions finalize reason-cli@3.1.0-linux
> 33 silly decomposeActions refresh-package-json reason-cli@3.1.0-linux
> 34 silly install executeActions
> 35 silly doSerial global-install 8
> 36 verbose correctMkdir /home/kenny/.npm/_locks correctMkdir not in flight; initializing
> 37 verbose lock using /home/kenny/.npm/_locks/staging-f31cd90535ff573e.lock for /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/.staging
> 38 silly doParallel extract 1
> 39 silly extract reason-cli@3.1.0-linux
> 40 silly tarball trying reason-cli@3.1.0-linux by hash: sha1-GxR73hi4VKwl+n9sjxYlKzktjqU=
> 41 silly extract reason-cli@3.1.0-linux extracted to /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/.staging/reason-cli-cce4205f (1488ms)
> 42 timing action:extract Completed in 1490ms
> 43 silly doReverseSerial unbuild 8
> 44 silly doSerial remove 8
> 45 silly doSerial move 8
> 46 silly doSerial finalize 8
> 47 silly finalize /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli
> 48 timing action:finalize Completed in 2ms
> 49 silly doParallel refresh-package-json 1
> 50 silly refresh-package-json /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli
> 51 timing action:refresh-package-json Completed in 8ms
> 52 silly doParallel preinstall 1
> 53 silly preinstall reason-cli@3.1.0-linux
> 54 info lifecycle reason-cli@3.1.0-linux~preinstall: reason-cli@3.1.0-linux
> 55 timing action:preinstall Completed in 0ms
> 56 silly doSerial build 8
> 57 silly build reason-cli@3.1.0-linux
> 58 info linkStuff reason-cli@3.1.0-linux
> 59 silly linkStuff reason-cli@3.1.0-linux has /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules as its parent node_modules
> 60 silly linkStuff reason-cli@3.1.0-linux is part of a global install
> 61 silly linkStuff reason-cli@3.1.0-linux is installed into a global node_modules
> 62 silly linkStuff reason-cli@3.1.0-linux is installed into the top-level global node_modules
> 63 verbose linkBins [ { ocamlmerlin: '.bin/ocamlmerlin',
> 63 verbose linkBins     'ocamlmerlin-reason': '.bin/ocamlmerlin-reason',
> 63 verbose linkBins     rtop: '.bin/rtop',
> 63 verbose linkBins     utop: '.bin/utop',
> 63 verbose linkBins     refmt: '.bin/refmt',
> 63 verbose linkBins     refmttype: '.bin/refmttype',
> 63 verbose linkBins     reopt: '.bin/reopt',
> 63 verbose linkBins     rebuild: '.bin/rebuild',
> 63 verbose linkBins     reactjs_jsx_ppx_v2: '.bin/reactjs_jsx_ppx_v2',
> 63 verbose linkBins     reactjs_jsx_ppx_v3: '.bin/reactjs_jsx_ppx_v3',
> 63 verbose linkBins     'reason-cli-esy-sandbox': '.bin/reason-cli-esy-sandbox' },
> 63 verbose linkBins   '/home/kenny/.nvm/versions/node/v10.0.0/bin',
> 63 verbose linkBins   true ]
> 64 timing action:build Completed in 5ms
> 65 silly doSerial global-link 8
> 66 silly doParallel update-linked 0
> 67 silly doSerial install 8
> 68 silly install reason-cli@3.1.0-linux
> 69 info lifecycle reason-cli@3.1.0-linux~install: reason-cli@3.1.0-linux
> 70 timing action:install Completed in 0ms
> 71 silly doSerial postinstall 8
> 72 silly postinstall reason-cli@3.1.0-linux
> 73 info lifecycle reason-cli@3.1.0-linux~postinstall: reason-cli@3.1.0-linux
> 74 verbose lifecycle reason-cli@3.1.0-linux~postinstall: unsafe-perm in lifecycle true
> 75 verbose lifecycle reason-cli@3.1.0-linux~postinstall: PATH: /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli/node_modules/.bin:/home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/.bin:/home/kenny/.nvm/versions/node/v10.0.0/bin:/usr/share/Modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
> 76 verbose lifecycle reason-cli@3.1.0-linux~postinstall: CWD: /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/reason-cli
> 77 silly lifecycle reason-cli@3.1.0-linux~postinstall: Args: [ '-c', './bin/esyBuildRelease bin install' ]
> 78 silly lifecycle reason-cli@3.1.0-linux~postinstall: Returned: code: 2  signal: null
> 79 info lifecycle reason-cli@3.1.0-linux~postinstall: Failed to exec postinstall script
> 80 timing action:postinstall Completed in 292ms
> 81 verbose unlock done using /home/kenny/.npm/_locks/staging-f31cd90535ff573e.lock for /home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/.staging
> 82 timing stage:rollbackFailedOptional Completed in 44ms
> 83 timing stage:runTopLevelLifecycles Completed in 2289ms
> 84 verbose stack Error: reason-cli@3.1.0-linux postinstall: `./bin/esyBuildRelease bin install`
> 84 verbose stack Exit status 2
> 84 verbose stack     at EventEmitter.<anonymous> (/home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
> 84 verbose stack     at EventEmitter.emit (events.js:182:13)
> 84 verbose stack     at ChildProcess.<anonymous> (/home/kenny/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 84 verbose stack     at ChildProcess.emit (events.js:182:13)
> 84 verbose stack     at maybeClose (internal/child_process.js:947:16)
> 84 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
> 85 verbose pkgid reason-cli@3.1.0-linux
> 86 verbose cwd /
> 87 verbose Linux 4.16.5-300.fc28.x86_64
> 88 verbose argv "/home/kenny/.nvm/versions/node/v10.0.0/bin/node" "/home/kenny/.nvm/versions/node/v10.0.0/bin/npm" "install" "-g" "reason-cli@3.1.0-linux"
> 89 verbose node v10.0.0
> 90 verbose npm  v6.0.0
> 91 error code ELIFECYCLE
> 92 error errno 2
> 93 error reason-cli@3.1.0-linux postinstall: `./bin/esyBuildRelease bin install`
> 93 error Exit status 2
> 94 error Failed at the reason-cli@3.1.0-linux postinstall script.
> 94 error This is probably not a problem with npm. There is likely additional logging output above.
> 95 verbose exit [ 2, true ]

**Comment by chenglou** [comment]
Can you try it without nvm?

**Comment by HristoKolev** [comment]
Here is the output from a brand new installation of Fedora 28 with the builtin node v8.11.2
```

[kenny@vm6 ~]$ npm install -g reason-cli@3.1.0-linux
/usr/bin/ocamlmerlin -> /usr/lib/node_modules/reason-cli/.bin/ocamlmerlin
/usr/bin/ocamlmerlin-reason -> /usr/lib/node_modules/reason-cli/.bin/ocamlmerlin-reason
/usr/bin/rtop -> /usr/lib/node_modules/reason-cli/.bin/rtop
/usr/bin/utop -> /usr/lib/node_modules/reason-cli/.bin/utop
/usr/bin/refmt -> /usr/lib/node_modules/reason-cli/.bin/refmt
/usr/bin/refmttype -> /usr/lib/node_modules/reason-cli/.bin/refmttype
/usr/bin/rebuild -> /usr/lib/node_modules/reason-cli/.bin/rebuild
/usr/bin/reopt -> /usr/lib/node_modules/reason-cli/.bin/reopt
/usr/bin/reactjs_jsx_ppx_v2 -> /usr/lib/node_modules/reason-cli/.bin/reactjs_jsx_ppx_v2
/usr/bin/reason-cli-esy-sandbox -> /usr/lib/node_modules/reason-cli/.bin/reason-cli-esy-sandbox
/usr/bin/reactjs_jsx_ppx_v3 -> /usr/lib/node_modules/reason-cli/.bin/reactjs_jsx_ppx_v3

> reason-cli@3.1.0-linux postinstall /usr/lib/node_modules/reason-cli
> ./bin/esyBuildRelease bin install

make: *** [/usr/lib/node_modules/reason-cli/r/build-eject/Makefile:1104: /usr/lib/node_modules/reason-cli/r/build-eject//bin/fastreplacestring.exe] Error 127
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! reason-cli@3.1.0-linux postinstall: `./bin/esyBuildRelease bin install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the reason-cli@3.1.0-linux postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kenny/.npm/_logs/2018-05-26T08_09_51_955Z-debug.log

```


There is the log file:
```

[kenny@vm6 ~]$ cat /home/kenny/.npm/_logs/2018-05-26T08_09_51_955Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'reason-cli@3.1.0-linux' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose npm-session fe6ad19bae958e9f
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/reason-cli 14ms (from cache)
8 silly pacote version manifest for reason-cli@3.1.0-linux fetched in 26ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule reason-cli@3.1.0-linux checking installable status
14 silly currentTree lib
15 silly idealTree lib
15 silly idealTree └── reason-cli@3.1.0-linux
16 silly install generateActionsToTake
17 silly diffTrees action count 1
18 silly diffTrees add reason-cli@3.1.0-linux
19 silly decomposeActions action count 8
20 silly decomposeActions fetch reason-cli@3.1.0-linux
21 silly decomposeActions extract reason-cli@3.1.0-linux
22 silly decomposeActions preinstall reason-cli@3.1.0-linux
23 silly decomposeActions build reason-cli@3.1.0-linux
24 silly decomposeActions install reason-cli@3.1.0-linux
25 silly decomposeActions postinstall reason-cli@3.1.0-linux
26 silly decomposeActions finalize reason-cli@3.1.0-linux
27 silly decomposeActions refresh-package-json reason-cli@3.1.0-linux
28 silly install executeActions
29 silly doSerial global-install 8
30 verbose correctMkdir /home/kenny/.npm/_locks correctMkdir not in flight; initializing
31 verbose makeDirectory /home/kenny/.npm/_locks creation not in flight; initializing
32 silly makeDirectory /home/kenny/.npm/_locks uid: 1000 gid: 1000
33 verbose lock using /home/kenny/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
34 silly doParallel extract 8
35 silly extract reason-cli@3.1.0-linux
36 silly pacote trying reason-cli@https://registry.npmjs.org/reason-cli/-/reason-cli-3.1.0-linux.tgz by hash: sha1-GxR73hi4VKwl+n9sjxYlKzktjqU=
37 silly pacote data for sha1-GxR73hi4VKwl+n9sjxYlKzktjqU= not present. Using manifest.
38 http fetch GET 200 https://registry.npmjs.org/reason-cli/-/reason-cli-3.1.0-linux.tgz 34478ms
39 silly pacote reason-cli@https://registry.npmjs.org/reason-cli/-/reason-cli-3.1.0-linux.tgz extracted in 34481ms
40 silly doReverseSerial unbuild 8
41 silly doSerial remove 8
42 silly doSerial move 8
43 silly doSerial finalize 8
44 silly finalize /usr/lib/node_modules/reason-cli
45 silly doParallel refresh-package-json 8
46 silly refresh-package-json /usr/lib/node_modules/reason-cli
47 silly doParallel preinstall 8
48 silly preinstall reason-cli@3.1.0-linux
49 info lifecycle reason-cli@3.1.0-linux~preinstall: reason-cli@3.1.0-linux
50 silly doSerial build 8
51 silly build reason-cli@3.1.0-linux
52 info linkStuff reason-cli@3.1.0-linux
53 silly linkStuff reason-cli@3.1.0-linux has /usr/lib/node_modules as its parent node_modules
54 silly linkStuff reason-cli@3.1.0-linux is part of a global install
55 silly linkStuff reason-cli@3.1.0-linux is installed into a global node_modules
56 silly linkStuff reason-cli@3.1.0-linux is installed into the top-level global node_modules
57 verbose linkBins reason-cli@3.1.0-linux
58 verbose linkBins [ { ocamlmerlin: '.bin/ocamlmerlin',
58 verbose linkBins     'ocamlmerlin-reason': '.bin/ocamlmerlin-reason',
58 verbose linkBins     rtop: '.bin/rtop',
58 verbose linkBins     utop: '.bin/utop',
58 verbose linkBins     refmt: '.bin/refmt',
58 verbose linkBins     refmttype: '.bin/refmttype',
58 verbose linkBins     reopt: '.bin/reopt',
58 verbose linkBins     rebuild: '.bin/rebuild',
58 verbose linkBins     reactjs_jsx_ppx_v2: '.bin/reactjs_jsx_ppx_v2',
58 verbose linkBins     reactjs_jsx_ppx_v3: '.bin/reactjs_jsx_ppx_v3',
58 verbose linkBins     'reason-cli-esy-sandbox': '.bin/reason-cli-esy-sandbox' },
58 verbose linkBins   '/usr/bin',
58 verbose linkBins   true ]
59 verbose linkMans reason-cli@3.1.0-linux
60 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/ocamlmerlin
61 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/ocamlmerlin-reason
62 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/rtop
63 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/utop
64 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/refmt
65 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/refmttype
66 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/rebuild
67 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/reopt
68 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/reactjs_jsx_ppx_v2
69 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/reason-cli-esy-sandbox
70 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/reactjs_jsx_ppx_v3
71 silly doSerial global-link 8
72 silly doParallel update-linked 8
73 silly doSerial install 8
74 silly install reason-cli@3.1.0-linux
75 info lifecycle reason-cli@3.1.0-linux~install: reason-cli@3.1.0-linux
76 silly doSerial postinstall 8
77 silly postinstall reason-cli@3.1.0-linux
78 info lifecycle reason-cli@3.1.0-linux~postinstall: reason-cli@3.1.0-linux
79 verbose lifecycle reason-cli@3.1.0-linux~postinstall: unsafe-perm in lifecycle true
80 verbose lifecycle reason-cli@3.1.0-linux~postinstall: PATH: /usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/reason-cli/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/kenny/.local/bin:/home/kenny/bin
81 verbose lifecycle reason-cli@3.1.0-linux~postinstall: CWD: /usr/lib/node_modules/reason-cli
82 silly lifecycle reason-cli@3.1.0-linux~postinstall: Args: [ '-c', './bin/esyBuildRelease bin install' ]
83 silly lifecycle reason-cli@3.1.0-linux~postinstall: Returned: code: 2  signal: null
84 info lifecycle reason-cli@3.1.0-linux~postinstall: Failed to exec postinstall script
85 verbose unlock done using /home/kenny/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
86 verbose stack Error: reason-cli@3.1.0-linux postinstall: `./bin/esyBuildRelease bin install`
86 verbose stack Exit status 2
86 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/index.js:285:16)
86 verbose stack     at emitTwo (events.js:126:13)
86 verbose stack     at EventEmitter.emit (events.js:214:7)
86 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/lib/spawn.js:55:14)
86 verbose stack     at emitTwo (events.js:126:13)
86 verbose stack     at ChildProcess.emit (events.js:214:7)
86 verbose stack     at maybeClose (internal/child_process.js:925:16)
86 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
87 verbose pkgid reason-cli@3.1.0-linux
88 verbose cwd /home/kenny
89 verbose Linux 4.16.11-300.fc28.x86_64
90 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "reason-cli@3.1.0-linux"
91 verbose node v8.11.2
92 verbose npm  v5.6.0
93 error code ELIFECYCLE
94 error errno 2
95 error reason-cli@3.1.0-linux postinstall: `./bin/esyBuildRelease bin install`
95 error Exit status 2
96 error Failed at the reason-cli@3.1.0-linux postinstall script.
96 error This is probably not a problem with npm. There is likely additional logging output above.
97 verbose exit [ 2, true ]

```

**Comment by andreypopp** [comment]
@HristoKolev Can you try `npm install -g reason-cli@3.2.0-linux`?

**Comment by HristoKolev** [comment]
I know, it failed the first time because of that. I gave it permissions.

**Comment by HristoKolev** [comment]
Ok. v3.2.0 fixes the problem for both the integrated node and the one managed by `nvm`.

Thank you very much.

**Comment by andreypopp** [comment]
Good, do you think the issue could be closed now, @HristoKolev?

**Comment by HristoKolev** [comment]
You can close it. Thank you again.
