### ISSUE TITLE
Cannot install neither using yarn nor npm on macOs

### ISSUE THREAD

**Issue by osenvosem** [reasonml/reason-cli#78]
npm 5.6.0, yarn 1.6.0, macOs 10.13.4

The process is stuck indefinitely in both cases.

![screen shot 2018-05-24 at 12 03 36](https://user-images.githubusercontent.com/6762673/40475748-fb769a14-5f4a-11e8-9a62-2019cf9d402a.jpg)
![screen shot 2018-05-24 at 12 05 36](https://user-images.githubusercontent.com/6762673/40475750-fbe6f728-5f4a-11e8-8f22-d44206f1b1bd.jpg)

**Comment by andreypopp** [comment]
@osenvosem Hi! Did you figure it out? It looks like it stalled due to poor network or something like that (the tarball is pretty big, around 120mb).

**Comment by osenvosem** [comment]
@andreypopp yep, you just should wait for a while, the package turned out to be very big. 🙂
And also if you have issues with it after the installation, you can try to install it with the `--unsafe-perm` flag.

**Comment by osenvosem** [comment]
@andreypopp it is macOs, but as I saw people on Linux are also experience this issue. I had an issue with not working ocamlmerlin `ocamlmerlin -version` gave me an error. The flag fixed that.
