### ISSUE TITLE
Incorrect conversion of custom fat arrow operator

### ISSUE THREAD

**Issue by jwhitley** [reasonml/reason-cli#98]
### Summary

`refmt` doesn't convert uses of an OCaml custom fat arrow operator `let (=>) ...` to Reason sensibly.

### Details and Example

The [opal parser combinator](https://github.com/pyrocat101/opal) defines the infix operator `=>`: [see opal.ml line 81](https://github.com/pyrocat101/opal/blob/master/opal.ml#L81).

`refmt` (and reason-tools) fail to convert this sanely, e.g.:

**OCaml**
```ocaml
let (=>) x f = x >>= fun r -> return (f r)
```

**Reason**
```reason
let (=>) = (x, f) => x >>= ((r) => return(f(r)));
```

The generated Reason code is invalid.  Opal's custom fat-arrow operator is silently left unchanged, which collides with Reason's choice to switch arrow function definition from thin arrow to fat arrow.  This causes obscure syntax errors later in the code at opal's point-of-use of its custom `=>` operator.  ([See use in `chainr1`](https://github.com/pyrocat101/opal/blob/master/opal.ml#L120))

### Suggestions

At minimum, `refmt` shouldn't let this invalid conversion pass silently – a warning or error should result.  As crazy-making as it seems, a policy of swapping custom `=>` (OCaml) for custom `->` (Reason) would at least allow a consistent automatic conversion and be guaranteed to not collide with some other user-defined OCaml operator.

**Comment by andreypopp** [comment]
The correct repo for this issue is https://github.com/facebook/reason

**Comment by jwhitley** [comment]
Acknowledged and thanks.  Closing this and reopening as facebook/reason#2416.
